### ISSUE TITLE
History (or search filtered history) < FRAME_SIZE breaks on startup

### ISSUE THREAD

**Issue by scbedd** [sbeddall/history-view#14]
```
hv --search="PerfStress" --c
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\repo\venv\Scripts\hv.exe\__main__.py", line 7, in <module>
  File "c:\repo\venv\lib\site-packages\hv\history_view.py", line 113, in console_entry
    renderer = HistoryRenderer(data, parrot_mode=args.parrotfy)
  File "c:\repo\venv\lib\site-packages\hv\renderer.py", line 71, in __init__
    raise InvalidConfigurationException(
hv.renderer.InvalidConfigurationException: Frame size of 10 is bigger than the size of the data array 5!
```

**Comment by semick-dev** [comment]
Fixed in #15
